# Generated by Django 5.2.17 on 2026-08-18 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Número de telefone no formato internacional normalizado (ex: 5511999999999).', max_length=32, unique=True, verbose_name='Telefone')),
                ('wa_id', models.CharField(blank=True, db_index=True, default='', help_text='ID do WhatsApp retornado pela Meta.', max_length=64, verbose_name='WhatsApp ID')),
                ('name', models.CharField(blank=True, default='', help_text='Nome do perfil do WhatsApp ou nome cadastrado.', max_length=255, verbose_name='Nome / Perfil')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais do contato.', verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contato WhatsApp',
                'verbose_name_plural': 'Contatos WhatsApp',
                'db_table': 'django_whatsapp_contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(blank=True, db_index=True, help_text='ID único da mensagem na Meta (wamid).', max_length=255, null=True, unique=True, verbose_name='WhatsApp Message ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (Recebida)'), ('outbound', 'Outbound (Enviada)')], db_index=True, max_length=10, verbose_name='Direção')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('template', 'Template'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento'), ('sticker', 'Figurinha'), ('location', 'Localização'), ('interactive', 'Interativo'), ('button', 'Botão'), ('reaction', 'Reação'), ('unknown', 'Desconhecido')], db_index=True, default='text', max_length=20, verbose_name='Tipo de Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou'), ('received', 'Recebida')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('body', models.TextField(blank=True, default='', verbose_name='Conteúdo / Texto')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload Bruto')),
                ('error_data', models.JSONField(blank=True, default=dict, verbose_name='Dados de Erro')),
                ('timestamp', models.DateTimeField(blank=True, help_text='Data e hora informadas pela Meta.', null=True, verbose_name='Timestamp Meta')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Falhou em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_whatsapp.whatsappcontact', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'db_table': 'django_whatsapp_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
